export PROMPT=':; '

export HISTSIZE=100000
export SAVEHIST=100000
export HISTFILE=~/.zsh_history

export EDITOR=vim
export VISUAL=$EDITOR

export LC_TIME=C
export TZ=UTC

if [ -f ~/.cargo/env ]; then
	source ~/.cargo/env
fi

bindkey -v
bindkey '^R' history-incremental-search-backward
